name: gmm-cryoem
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - jupyter=1.0.0
  - pandas=1.0.1
  - python=3.7.6
  - matplotlib=3.1.3
  - numpy=1.18.1
  - plotly=4.5.2
  - requests
  - scipy

