name: gmm-cryoem
channels:
  - conda-forge
  - omnia
  - defaults
  - astra-toolbox
dependencies:
  - ipyvolume
  - plotly
  - pandas
  - scipy
  - jupyter
  - numpy
  - python=3.6
  - scikit-learn
  - matplotlib
  - requests
  - astra-toolbox

